import type { Meta, StoryObj } from '@storybook/react';

import EpisodeList from './EpisodeList';

const meta: Meta<typeof EpisodeList> = {
  component: EpisodeList,
};

export default meta;
type Story = StoryObj<typeof EpisodeList>;

export const Default: Story = {
  args: {
    showCount: true,
    episodes: [
      {
        air_date: '2021-06-09',
        episode_number: 1,
        episode_type: 'standard',
        id: 2534997,
        name: 'Glorious Purpose',
        overview: 'After stealing the Tesseract in "Avengers: Endgame," Loki lands before the Time Variance Authority.',
        production_code: '',
        runtime: 53,
        season_number: 1,
        show_id: 84958,
        still_path: '/gxh0k3aADsYkt9tgkfm2kGn2qQj.jpg',
        vote_average: 7.212,
        vote_count: 153,
        crew: [],
        guest_stars: [],
      },
      {
        air_date: '2021-06-16',
        episode_number: 2,
        episode_type: 'standard',
        id: 2927202,
        name: 'The Variant',
        overview: "Mobius puts Loki to work, but not everyone at TVA is thrilled about the God of Mischief's presence.",
        production_code: '',
        runtime: 56,
        season_number: 1,
        show_id: 84958,
        still_path: '/gqpcfkdmSsm6xiX2EsLkwUvA8g8.jpg',
        vote_average: 7.867,
        vote_count: 113,
        crew: [],
        guest_stars: [],
      },
      {
        air_date: '2021-06-23',
        episode_number: 3,
        episode_type: 'standard',
        id: 2927203,
        name: 'Lamentis',
        overview: "Loki finds out The Variant's plans, but he has his own that will forever alter both their destinies.",
        production_code: '',
        runtime: 44,
        season_number: 1,
        show_id: 84958,
        still_path: '/aTjfWml9Prd8cUB9cfk8yOAEh7v.jpg',
        vote_average: 7.389,
        vote_count: 104,
        crew: [],
        guest_stars: [],
      },
      {
        air_date: '2021-06-30',
        episode_number: 4,
        episode_type: 'standard',
        id: 2927204,
        name: 'The Nexus Event',
        overview: 'Frayed nerves and paranoia infiltrate the TVA as Mobius and Hunter B-15 search for Loki and Sylvie.',
        production_code: '',
        runtime: 50,
        season_number: 1,
        show_id: 84958,
        still_path: '/niIXLqEr98mnQuYuMuEvq9Y6OQa.jpg',
        vote_average: 8.199,
        vote_count: 103,
        crew: [],
        guest_stars: [],
      },
      {
        air_date: '2021-07-07',
        episode_number: 5,
        episode_type: 'standard',
        id: 2927205,
        name: 'Journey Into Mystery',
        overview: 'Loki tries to escape The Void, a desolate purgatory where he meets variant versions of himself.',
        production_code: '',
        runtime: 51,
        season_number: 1,
        show_id: 84958,
        still_path: '/5fRAAO13URmteku8mb39V9YPJBb.jpg',
        vote_average: 8.158,
        vote_count: 95,
        crew: [],
        guest_stars: [],
      },
      {
        air_date: '2021-07-14',
        episode_number: 6,
        episode_type: 'finale',
        id: 2927206,
        name: 'For All Time. Always.',
        overview: 'The clock is ticking in the season finale which finds Loki and Sylvie on a date with destiny.',
        production_code: '',
        runtime: 48,
        season_number: 1,
        show_id: 84958,
        still_path: '/98hGgYbNFP8GnZhJzAar22bWIAT.jpg',
        vote_average: 8.153,
        vote_count: 95,
        crew: [],
        guest_stars: [],
      },
    ],
  },
};
