import type { Meta, StoryObj } from '@storybook/react';
import Cast from '../Cards/Cast';
import HorizontalScroller from './HorizontalScroller';

const casts = [
  {
    adult: false,
    gender: 2,
    id: 2037,
    known_for_department: 'Acting',
    name: 'Cillian Murphy',
    original_name: 'Cillian Murphy',
    popularity: 55.987,
    profile_path: '/2lKs67r7FI4bPu0AXxMUJZxmUXn.jpg',
    cast_id: 3,
    character: 'J. Robert Oppenheimer',
    credit_id: '613a940d9653f60043e380df',
    order: 0,
  },
  {
    adult: false,
    gender: 1,
    id: 5081,
    known_for_department: 'Acting',
    name: 'Emily Blunt',
    original_name: 'Emily Blunt',
    popularity: 69.262,
    profile_path: '/5nCSG5TL1bP1geD8aaBfaLnLLCD.jpg',
    cast_id: 161,
    character: 'Kitty Oppenheimer',
    credit_id: '6328c918524978007e9f1a7f',
    order: 1,
  },
  {
    adult: false,
    gender: 2,
    id: 1892,
    known_for_department: 'Acting',
    name: 'Matt Damon',
    original_name: 'Matt Damon',
    popularity: 74.1,
    profile_path: '/At3JgvaNeEN4Z4ESKlhhes85Xo3.jpg',
    cast_id: 108,
    character: 'Leslie Groves',
    credit_id: '6328ad9843250f00830efdca',
    order: 2,
  },
  {
    adult: false,
    gender: 2,
    id: 3223,
    known_for_department: 'Acting',
    name: 'Robert Downey Jr.',
    original_name: 'Robert Downey Jr.',
    popularity: 44.322,
    profile_path: '/im9SAqJPZKEbVZGmjXuLI4O7RvM.jpg',
    cast_id: 109,
    character: 'Lewis Strauss',
    credit_id: '6328adb143250f00830efdd6',
    order: 3,
  },
  {
    adult: false,
    gender: 1,
    id: 1373737,
    known_for_department: 'Acting',
    name: 'Florence Pugh',
    original_name: 'Florence Pugh',
    popularity: 93.428,
    profile_path: '/f8e41Oon18FiEZr4zgyJDVUqOeh.jpg',
    cast_id: 110,
    character: 'Jean Tatlock',
    credit_id: '6328adc8229ae2007e7a4fbc',
    order: 4,
  },
  {
    adult: false,
    gender: 2,
    id: 2299,
    known_for_department: 'Acting',
    name: 'Josh Hartnett',
    original_name: 'Josh Hartnett',
    popularity: 34.687,
    profile_path: '/dCfu2EN7FjISACcjilaJu7evwEc.jpg',
    cast_id: 113,
    character: 'Ernest Lawrence',
    credit_id: '6328adf543250f007e8c215e',
    order: 5,
  },
  {
    adult: false,
    gender: 2,
    id: 1893,
    known_for_department: 'Acting',
    name: 'Casey Affleck',
    original_name: 'Casey Affleck',
    popularity: 37.933,
    profile_path: '/vD5MtCjHPHpmU9XNn74EPGMHT7o.jpg',
    cast_id: 129,
    character: 'Boris Pash',
    credit_id: '6328af3691b530007d0c4cff',
    order: 6,
  },
  {
    adult: false,
    gender: 2,
    id: 17838,
    known_for_department: 'Acting',
    name: 'Rami Malek',
    original_name: 'Rami Malek',
    popularity: 47.178,
    profile_path: '/ewr46CGOdsx5NzAJdIzEBz2yIQh.jpg',
    cast_id: 111,
    character: 'David Hill',
    credit_id: '6328add420af7700998bc29b',
    order: 7,
  },
  {
    adult: false,
    gender: 2,
    id: 11181,
    known_for_department: 'Acting',
    name: 'Kenneth Branagh',
    original_name: 'Kenneth Branagh',
    popularity: 32.56,
    profile_path: '/AbCqqFxNi5w3nDUFdQt0DGMFh5H.jpg',
    cast_id: 121,
    character: 'Niels Bohr',
    credit_id: '6328aeb0124c8d007d63c035',
    order: 8,
  },
  {
    adult: false,
    gender: 2,
    id: 227564,
    known_for_department: 'Directing',
    name: 'Benny Safdie',
    original_name: 'Benny Safdie',
    popularity: 14.153,
    profile_path: '/gidElVVlUGeAby1trDGW9DlxLh5.jpg',
    cast_id: 112,
    character: 'Edward Teller',
    credit_id: '6328ade55cea18009106ac6f',
    order: 9,
  },
  {
    adult: false,
    gender: 2,
    id: 76512,
    known_for_department: 'Acting',
    name: 'Jason Clarke',
    original_name: 'Jason Clarke',
    popularity: 18.107,
    profile_path: '/jGMOmi7LxpSO6842gJOZKt1gs9N.jpg',
    cast_id: 123,
    character: 'Roger Robb',
    credit_id: '6328aed1b18f32007b7c4823',
    order: 10,
  },
  {
    adult: false,
    gender: 2,
    id: 1039523,
    known_for_department: 'Acting',
    name: 'Dylan Arnold',
    original_name: 'Dylan Arnold',
    popularity: 19.745,
    profile_path: '/ipmcpPccYlVqBDiKnE3LGhaePuP.jpg',
    cast_id: 117,
    character: 'Frank Oppenheimer',
    credit_id: '6328ae3b124c8d007d63c00e',
    order: 11,
  },
  {
    adult: false,
    gender: 2,
    id: 71010,
    known_for_department: 'Acting',
    name: 'Tom Conti',
    original_name: 'Tom Conti',
    popularity: 20.816,
    profile_path: '/aeyH3jaaauYakZS3CWbmRPg6J10.jpg',
    cast_id: 351,
    character: 'Albert Einstein',
    credit_id: '6458b3c71b70ae00fd6ad2f3',
    order: 12,
  },
  {
    adult: false,
    gender: 2,
    id: 19655,
    known_for_department: 'Acting',
    name: "James D'Arcy",
    original_name: "James D'Arcy",
    popularity: 23.606,
    profile_path: '/6CInTvBeLwXLx2id9TgaULaVEO4.jpg',
    cast_id: 133,
    character: 'Patrick Blackett',
    credit_id: '6328af6bd7a70a0081cead20',
    order: 13,
  },
  {
    adult: false,
    gender: 2,
    id: 83854,
    known_for_department: 'Acting',
    name: 'David Dastmalchian',
    original_name: 'David Dastmalchian',
    popularity: 25.301,
    profile_path: '/o9oOnTUbsFVYzifDZDdwrsAidy8.jpg',
    cast_id: 122,
    character: 'William Borden',
    credit_id: '6328aec6ac8e6b007d5d3ef5',
    order: 14,
  },
  {
    adult: false,
    gender: 2,
    id: 122889,
    known_for_department: 'Acting',
    name: 'Dane DeHaan',
    original_name: 'Dane DeHaan',
    popularity: 33.901,
    profile_path: '/vZ7ix8UeRYgepFPFc4FIVKDLKDX.jpg',
    cast_id: 114,
    character: 'Kenneth Nichols',
    credit_id: '6328ae0193bd69007a95d6a4',
    order: 15,
  },
  {
    adult: false,
    gender: 2,
    id: 71375,
    known_for_department: 'Acting',
    name: 'Alden Ehrenreich',
    original_name: 'Alden Ehrenreich',
    popularity: 14.533,
    profile_path: '/bx86TPUmeHp0QkijQb16r2qIwEr.jpg',
    cast_id: 118,
    character: 'Senate Aide',
    credit_id: '6328ae59ac8e6b007aabf20a',
    order: 16,
  },
];

const meta: Meta<typeof HorizontalScroller> = {
  component: HorizontalScroller,
};

export default meta;

type Story = StoryObj<typeof HorizontalScroller>;

export const Default: Story = {
  args: {
    children: casts.map((cast, index) => <Cast cast={cast} key={index} />),
    gap: 'md',
  },
};
