import type { Meta, StoryObj } from '@storybook/react';

import { CastMember } from '@lib/features/Movie/types';
import CastCarousel from './CastCarousel';

const meta: Meta<typeof CastCarousel> = {
  component: CastCarousel,
};

export default meta;

type Story = StoryObj<typeof CastCarousel<CastMember, keyof CastMember, keyof CastMember, keyof CastMember, keyof CastMember>>;

export const Default: Story = {
  args: {
    id_path: 'id',
    profile_path: 'profile_path',
    name_path: 'name',
    character_path: 'character',
    casts: [
      {
        adult: false,
        gender: 2,
        id: 2037,
        known_for_department: 'Acting',
        name: 'Cillian Murphy',
        original_name: 'Cillian Murphy',
        popularity: 55.987,
        profile_path: '/2lKs67r7FI4bPu0AXxMUJZxmUXn.jpg',
        cast_id: 3,
        character: 'J. Robert Oppenheimer',
        credit_id: '613a940d9653f60043e380df',
        order: 0,
      },
      {
        adult: false,
        gender: 1,
        id: 5081,
        known_for_department: 'Acting',
        name: 'Emily Blunt',
        original_name: 'Emily Blunt',
        popularity: 69.262,
        profile_path: '/5nCSG5TL1bP1geD8aaBfaLnLLCD.jpg',
        cast_id: 161,
        character: 'Kitty Oppenheimer',
        credit_id: '6328c918524978007e9f1a7f',
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 1892,
        known_for_department: 'Acting',
        name: 'Matt Damon',
        original_name: 'Matt Damon',
        popularity: 74.1,
        profile_path: '/At3JgvaNeEN4Z4ESKlhhes85Xo3.jpg',
        cast_id: 108,
        character: 'Leslie Groves',
        credit_id: '6328ad9843250f00830efdca',
        order: 2,
      },
      {
        adult: false,
        gender: 2,
        id: 3223,
        known_for_department: 'Acting',
        name: 'Robert Downey Jr.',
        original_name: 'Robert Downey Jr.',
        popularity: 44.322,
        profile_path: '/im9SAqJPZKEbVZGmjXuLI4O7RvM.jpg',
        cast_id: 109,
        character: 'Lewis Strauss',
        credit_id: '6328adb143250f00830efdd6',
        order: 3,
      },
      {
        adult: false,
        gender: 1,
        id: 1373737,
        known_for_department: 'Acting',
        name: 'Florence Pugh',
        original_name: 'Florence Pugh',
        popularity: 93.428,
        profile_path: '/f8e41Oon18FiEZr4zgyJDVUqOeh.jpg',
        cast_id: 110,
        character: 'Jean Tatlock',
        credit_id: '6328adc8229ae2007e7a4fbc',
        order: 4,
      },
      {
        adult: false,
        gender: 2,
        id: 2299,
        known_for_department: 'Acting',
        name: 'Josh Hartnett',
        original_name: 'Josh Hartnett',
        popularity: 34.687,
        profile_path: '/dCfu2EN7FjISACcjilaJu7evwEc.jpg',
        cast_id: 113,
        character: 'Ernest Lawrence',
        credit_id: '6328adf543250f007e8c215e',
        order: 5,
      },
      {
        adult: false,
        gender: 2,
        id: 1893,
        known_for_department: 'Acting',
        name: 'Casey Affleck',
        original_name: 'Casey Affleck',
        popularity: 37.933,
        profile_path: '/vD5MtCjHPHpmU9XNn74EPGMHT7o.jpg',
        cast_id: 129,
        character: 'Boris Pash',
        credit_id: '6328af3691b530007d0c4cff',
        order: 6,
      },
      {
        adult: false,
        gender: 2,
        id: 17838,
        known_for_department: 'Acting',
        name: 'Rami Malek',
        original_name: 'Rami Malek',
        popularity: 47.178,
        profile_path: '/ewr46CGOdsx5NzAJdIzEBz2yIQh.jpg',
        cast_id: 111,
        character: 'David Hill',
        credit_id: '6328add420af7700998bc29b',
        order: 7,
      },
      {
        adult: false,
        gender: 2,
        id: 11181,
        known_for_department: 'Acting',
        name: 'Kenneth Branagh',
        original_name: 'Kenneth Branagh',
        popularity: 32.56,
        profile_path: '/AbCqqFxNi5w3nDUFdQt0DGMFh5H.jpg',
        cast_id: 121,
        character: 'Niels Bohr',
        credit_id: '6328aeb0124c8d007d63c035',
        order: 8,
      },
      {
        adult: false,
        gender: 2,
        id: 227564,
        known_for_department: 'Directing',
        name: 'Benny Safdie',
        original_name: 'Benny Safdie',
        popularity: 14.153,
        profile_path: '/gidElVVlUGeAby1trDGW9DlxLh5.jpg',
        cast_id: 112,
        character: 'Edward Teller',
        credit_id: '6328ade55cea18009106ac6f',
        order: 9,
      },
      {
        adult: false,
        gender: 2,
        id: 76512,
        known_for_department: 'Acting',
        name: 'Jason Clarke',
        original_name: 'Jason Clarke',
        popularity: 18.107,
        profile_path: '/jGMOmi7LxpSO6842gJOZKt1gs9N.jpg',
        cast_id: 123,
        character: 'Roger Robb',
        credit_id: '6328aed1b18f32007b7c4823',
        order: 10,
      },
      {
        adult: false,
        gender: 2,
        id: 1039523,
        known_for_department: 'Acting',
        name: 'Dylan Arnold',
        original_name: 'Dylan Arnold',
        popularity: 19.745,
        profile_path: '/ipmcpPccYlVqBDiKnE3LGhaePuP.jpg',
        cast_id: 117,
        character: 'Frank Oppenheimer',
        credit_id: '6328ae3b124c8d007d63c00e',
        order: 11,
      },
      {
        adult: false,
        gender: 2,
        id: 71010,
        known_for_department: 'Acting',
        name: 'Tom Conti',
        original_name: 'Tom Conti',
        popularity: 20.816,
        profile_path: '/aeyH3jaaauYakZS3CWbmRPg6J10.jpg',
        cast_id: 351,
        character: 'Albert Einstein',
        credit_id: '6458b3c71b70ae00fd6ad2f3',
        order: 12,
      },
      {
        adult: false,
        gender: 2,
        id: 19655,
        known_for_department: 'Acting',
        name: "James D'Arcy",
        original_name: "James D'Arcy",
        popularity: 23.606,
        profile_path: '/6CInTvBeLwXLx2id9TgaULaVEO4.jpg',
        cast_id: 133,
        character: 'Patrick Blackett',
        credit_id: '6328af6bd7a70a0081cead20',
        order: 13,
      },
      {
        adult: false,
        gender: 2,
        id: 83854,
        known_for_department: 'Acting',
        name: 'David Dastmalchian',
        original_name: 'David Dastmalchian',
        popularity: 25.301,
        profile_path: '/o9oOnTUbsFVYzifDZDdwrsAidy8.jpg',
        cast_id: 122,
        character: 'William Borden',
        credit_id: '6328aec6ac8e6b007d5d3ef5',
        order: 14,
      },
      {
        adult: false,
        gender: 2,
        id: 122889,
        known_for_department: 'Acting',
        name: 'Dane DeHaan',
        original_name: 'Dane DeHaan',
        popularity: 33.901,
        profile_path: '/vZ7ix8UeRYgepFPFc4FIVKDLKDX.jpg',
        cast_id: 114,
        character: 'Kenneth Nichols',
        credit_id: '6328ae0193bd69007a95d6a4',
        order: 15,
      },
      {
        adult: false,
        gender: 2,
        id: 71375,
        known_for_department: 'Acting',
        name: 'Alden Ehrenreich',
        original_name: 'Alden Ehrenreich',
        popularity: 14.533,
        profile_path: '/bx86TPUmeHp0QkijQb16r2qIwEr.jpg',
        cast_id: 118,
        character: 'Senate Aide',
        credit_id: '6328ae59ac8e6b007aabf20a',
        order: 16,
      },
      {
        adult: false,
        gender: 2,
        id: 3417,
        known_for_department: 'Acting',
        name: 'Tony Goldwyn',
        original_name: 'Tony Goldwyn',
        popularity: 26.808,
        profile_path: '/kLuvuxspqKvR2F8zk3Gc1b0KhkQ.jpg',
        cast_id: 127,
        character: 'Gordon Gray',
        credit_id: '6328af190f21c6007faaa1bf',
        order: 17,
      },
      {
        adult: false,
        gender: 2,
        id: 109322,
        known_for_department: 'Acting',
        name: 'Jefferson Hall',
        original_name: 'Jefferson Hall',
        popularity: 19.776,
        profile_path: '/rUhREsWITBvyoPdLiPJOadAwRYq.jpg',
        cast_id: 355,
        character: 'Haakon Chevalier',
        credit_id: '64b31f5478570e011da9095e',
        order: 18,
      },
      {
        adult: false,
        gender: 2,
        id: 38582,
        known_for_department: 'Acting',
        name: 'David Krumholtz',
        original_name: 'David Krumholtz',
        popularity: 25.529,
        profile_path: '/6M2kk44Z1DyUhuVGyy2UDbCKZuM.jpg',
        cast_id: 119,
        character: 'Isidor Rabi',
        credit_id: '6328ae8320af7700998bc2d3',
        order: 19,
      },
      {
        adult: false,
        gender: 2,
        id: 8654,
        known_for_department: 'Acting',
        name: 'Matthew Modine',
        original_name: 'Matthew Modine',
        popularity: 29.912,
        profile_path: '/z974QEHL12qUvLyk6hlWGAmDgom.jpg',
        cast_id: 116,
        character: 'Vannevar Bush',
        credit_id: '6328ae2a93bd69007a95d6b5',
        order: 20,
      },
      {
        adult: false,
        gender: 2,
        id: 35091,
        known_for_department: 'Acting',
        name: 'Scott Grimes',
        original_name: 'Scott Grimes',
        popularity: 16.067,
        profile_path: '/oB0xperEt45g8Ti6lpObpi6c5XV.jpg',
        cast_id: 131,
        character: 'Counsel',
        credit_id: '6328af4ed7a70a007c79bfe9',
        order: 21,
      },
      {
        adult: false,
        gender: 2,
        id: 1519972,
        known_for_department: 'Acting',
        name: 'Kurt Koehler',
        original_name: 'Kurt Koehler',
        popularity: 2.898,
        profile_path: '/3MG6176YLqawWp3sjzOMUkiysik.jpg',
        cast_id: 358,
        character: 'Thomas Morgan',
        credit_id: '64bb3543af85de010018d60a',
        order: 22,
      },
      {
        adult: false,
        gender: 2,
        id: 154583,
        known_for_department: 'Acting',
        name: 'John Gowans',
        original_name: 'John Gowans',
        popularity: 3.928,
        profile_path: '/v1j1HB2Kbg64wXUkivmBrKd3lYa.jpg',
        cast_id: 359,
        character: 'Ward Evans',
        credit_id: '64bb354ceb79c2013969de6d',
        order: 23,
      },
      {
        adult: false,
        gender: 2,
        id: 209513,
        known_for_department: 'Acting',
        name: 'Macon Blair',
        original_name: 'Macon Blair',
        popularity: 11.539,
        profile_path: '/5QkTsGL3deaZTNTTcQ1iKA72Y8o.jpg',
        cast_id: 360,
        character: 'Lloyd Garrison',
        credit_id: '64bb3559e9da6900cb7b38a3',
        order: 24,
      },
      {
        adult: false,
        gender: 2,
        id: 35518,
        known_for_department: 'Acting',
        name: 'Harry Groener',
        original_name: 'Harry Groener',
        popularity: 7.318,
        profile_path: '/3MAsDC1JtNqef1O4MwqakGjJkkI.jpg',
        cast_id: 361,
        character: 'Senator McGee',
        credit_id: '64bb356285c0a200c8973d97',
        order: 25,
      },
      {
        adult: false,
        gender: 2,
        id: 24360,
        known_for_department: 'Acting',
        name: 'Gregory Jbara',
        original_name: 'Gregory Jbara',
        popularity: 9.265,
        profile_path: '/nYkdyh9E0iNuue8k4437gCWD70G.jpg',
        cast_id: 362,
        character: 'Chairman Magnuson',
        credit_id: '64bb356bfd4a9600c8ba7a16',
        order: 26,
      },
      {
        adult: false,
        gender: 2,
        id: 1221560,
        known_for_department: 'Acting',
        name: 'Ted King',
        original_name: 'Ted King',
        popularity: 7.673,
        profile_path: '/6bQ6IGT8lPzDM8Pr7kQ1VfeXREO.jpg',
        cast_id: 363,
        character: 'Senator Bartlett',
        credit_id: '64bb357cac6c7900afd4fa57',
        order: 27,
      },
      {
        adult: false,
        gender: 2,
        id: 76001,
        known_for_department: 'Acting',
        name: 'Tim DeKay',
        original_name: 'Tim DeKay',
        popularity: 13.464,
        profile_path: '/m62gS0B5fcQfFpoq2tmJVfpE43x.jpg',
        cast_id: 364,
        character: 'Senator Pastore',
        credit_id: '64bb3583eb79c200ac80d08c',
        order: 28,
      },
      {
        adult: false,
        gender: 2,
        id: 1215064,
        known_for_department: 'Acting',
        name: 'Steven Houska',
        original_name: 'Steven Houska',
        popularity: 1.4,
        profile_path: '/aZHLD1QOEc90t8pJ3SU6T5OmGFa.jpg',
        cast_id: 365,
        character: 'Senator Scott',
        credit_id: '64bb358be9da6900ece97d0f',
        order: 29,
      },
      {
        adult: false,
        gender: 2,
        id: 2781676,
        known_for_department: 'Acting',
        name: 'Petrie Willink',
        original_name: 'Petrie Willink',
        popularity: 1.714,
        profile_path: '/gjxKOLnBNkS3lGpRrVreLC4DwgY.jpg',
        cast_id: 155,
        character: 'Dutch Student',
        credit_id: '6328b1b6124c8d007a793b09',
        order: 30,
      },
      {
        adult: false,
        gender: 2,
        id: 16808,
        known_for_department: 'Acting',
        name: 'Matthias Schweighöfer',
        original_name: 'Matthias Schweighöfer',
        popularity: 16.672,
        profile_path: '/i4c5JjvC5EpecZbp4J96mFmtm0Z.jpg',
        cast_id: 139,
        character: 'Werner Heisenberg',
        credit_id: '6328afccbc2cb3008334a66c',
        order: 31,
      },
      {
        adult: false,
        gender: 2,
        id: 934281,
        known_for_department: 'Acting',
        name: 'Alex Wolff',
        original_name: 'Alex Wolff',
        popularity: 22.12,
        profile_path: '/hMhGWS5nB7ZGA3B1aefY39pizgm.jpg',
        cast_id: 126,
        character: 'Luis Alvarez',
        credit_id: '6328af075cea18009106acb2',
        order: 32,
      },
      {
        adult: false,
        gender: 2,
        id: 62816,
        known_for_department: 'Acting',
        name: 'Josh Zuckerman',
        original_name: 'Josh Zuckerman',
        popularity: 9.574,
        profile_path: '/kb0oEHc1a3lZUoPXaSyccfinFOP.jpg',
        cast_id: 142,
        character: 'Rossi Lomanitz',
        credit_id: '6328aff6ac8e6b007aabf277',
        order: 33,
      },
      {
        adult: false,
        gender: 2,
        id: 1675638,
        known_for_department: 'Acting',
        name: 'Rory Keane',
        original_name: 'Rory Keane',
        popularity: 1.4,
        profile_path: '/hbv61xBI0sQSKg9APeiLUu9DLcd.jpg',
        cast_id: 366,
        character: 'Hartland Snyder',
        credit_id: '64bb35abac6c7900afd4fa76',
        order: 34,
      },
      {
        adult: false,
        gender: 2,
        id: 11665,
        known_for_department: 'Acting',
        name: 'Michael Angarano',
        original_name: 'Michael Angarano',
        popularity: 17.735,
        profile_path: '/q4SOVndGsnCmSZKBllLaJCNM72c.jpg',
        cast_id: 120,
        character: 'Robert Serber',
        credit_id: '6328ae99d7a70a007c79bfbe',
        order: 35,
      },
      {
        adult: false,
        gender: 1,
        id: 968089,
        known_for_department: 'Acting',
        name: 'Emma Dumont',
        original_name: 'Emma Dumont',
        popularity: 19.383,
        profile_path: '/ewbPhI5SRsOFFkHFaIO6Fk24Zfn.jpg',
        cast_id: 138,
        character: 'Jackie Oppenheimer',
        credit_id: '6328afbdb18f32007b7c4852',
        order: 36,
      },
      {
        adult: false,
        gender: 1,
        id: 154615,
        known_for_department: 'Acting',
        name: 'Sadie Stratton',
        original_name: 'Sadie Stratton',
        popularity: 3.229,
        profile_path: '/zsWcj39NbRNYURAg25PP9cAiszc.jpg',
        cast_id: 367,
        character: 'Mary Washburn',
        credit_id: '64bb35c1e9da6900af703d99',
        order: 37,
      },
      {
        adult: false,
        gender: 1,
        id: 3952653,
        known_for_department: 'Acting',
        name: 'Britt Kyle',
        original_name: 'Britt Kyle',
        popularity: 1.06,
        profile_path: '/u57rMMDOqoNaElIt5X3ykCetDLO.jpg',
        cast_id: 368,
        character: 'Barbara Chevalier',
        credit_id: '64bb35dcfd4a9600ae647feb',
        order: 38,
      },
      {
        adult: false,
        gender: 2,
        id: 545195,
        known_for_department: 'Acting',
        name: 'Guy Burnet',
        original_name: 'Guy Burnet',
        popularity: 12.924,
        profile_path: '/ksxpXRLJplv8kSfEHPYdboIwNfi.jpg',
        cast_id: 135,
        character: 'George Eltenton',
        credit_id: '6328af8dbbd0b0008217ba06',
        order: 39,
      },
      {
        adult: false,
        gender: 2,
        id: 2692405,
        known_for_department: 'Acting',
        name: 'Tom Jenkins',
        original_name: 'Tom Jenkins',
        popularity: 6.711,
        profile_path: '/qfALI1iNFbc2xNxL9qGPDhlkMkE.jpg',
        cast_id: 162,
        character: 'Richard Tolman',
        credit_id: '6328d10ea3b5e60091f5086c',
        order: 40,
      },
      {
        adult: false,
        gender: 1,
        id: 20805,
        known_for_department: 'Acting',
        name: 'Louise Lombard',
        original_name: 'Louise Lombard',
        popularity: 21.184,
        profile_path: '/6znYbOI2Z8PfzZ6p9jHG5QdAeb2.jpg',
        cast_id: 130,
        character: 'Ruth Tolman',
        credit_id: '6328af45229ae2007e7a5013',
        order: 41,
      },
      {
        adult: false,
        gender: 2,
        id: 1720614,
        known_for_department: 'Acting',
        name: 'Michael Andrew Baker',
        original_name: 'Michael Andrew Baker',
        popularity: 4.934,
        profile_path: '/yww1ArQy1dRZFu5w7iwpT7AhSfe.jpg',
        cast_id: 369,
        character: 'Joe Volpe',
        credit_id: '64bb35fa9d592c013ebd0c03',
        order: 42,
      },
      {
        adult: false,
        gender: 2,
        id: 212689,
        known_for_department: 'Acting',
        name: 'Jeff Hephner',
        original_name: 'Jeff Hephner',
        popularity: 6.932,
        profile_path: '/qlIzEnBEuLT9ofE1PCGKKHHGga2.jpg',
        cast_id: 147,
        character: 'Congressman',
        credit_id: '6328b0c8dcb6a30085b4b9f1',
        order: 43,
      },
      {
        adult: false,
        gender: 2,
        id: 1493745,
        known_for_department: 'Acting',
        name: 'Olli Haaskivi',
        original_name: 'Olli Haaskivi',
        popularity: 3.673,
        profile_path: '/1KGmjiV9ffm1OMB0ybpdunawswf.jpg',
        cast_id: 144,
        character: 'Edward Condon',
        credit_id: '6328b00db18f32008013717d',
        order: 44,
      },
      {
        adult: false,
        gender: 2,
        id: 1541178,
        known_for_department: 'Acting',
        name: 'David Rysdahl',
        original_name: 'David Rysdahl',
        popularity: 9.113,
        profile_path: '/yYTsO3nH4ikZJ3K2XTgQASEOWiU.jpg',
        cast_id: 163,
        character: 'Donald Hornig',
        credit_id: '6328d1f6c51acd007d5dc639',
        order: 45,
      },
      {
        adult: false,
        gender: 2,
        id: 15760,
        known_for_department: 'Acting',
        name: 'Josh Peck',
        original_name: 'Josh Peck',
        popularity: 13.541,
        profile_path: '/qoapD8slSdb550o1JEoepv1SvT0.jpg',
        cast_id: 124,
        character: 'Kenneth Bainbridge',
        credit_id: '6328aee393bd6900822df8cd',
        order: 46,
      },
      {
        adult: false,
        gender: 2,
        id: 1030513,
        known_for_department: 'Acting',
        name: 'Jack Quaid',
        original_name: 'Jack Quaid',
        popularity: 25.499,
        profile_path: '/nI6ULvUIxxajya5DeTxcCdV3cal.jpg',
        cast_id: 115,
        character: 'Richard Feynman',
        credit_id: '6328ae0a0f21c6007cba2a50',
        order: 47,
      },
      {
        adult: false,
        gender: 2,
        id: 64213,
        known_for_department: 'Acting',
        name: 'Brett DelBuono',
        original_name: 'Brett DelBuono',
        popularity: 4.61,
        profile_path: '/fw41lI6WAHURQymZHMf6cY6pznH.jpg',
        cast_id: 370,
        character: 'Concerned Scientist',
        credit_id: '64bb3625fd4a9600ae64801b',
        order: 48,
      },
      {
        adult: false,
        gender: 2,
        id: 63764,
        known_for_department: 'Acting',
        name: 'Gustaf Skarsgård',
        original_name: 'Gustaf Skarsgård',
        popularity: 31.091,
        profile_path: '/oH2XSFil6ZHNg9HWur1ymwTLRX3.jpg',
        cast_id: 140,
        character: 'Hans Bethe',
        credit_id: '6328afd953866e0085b129cc',
        order: 49,
      },
      {
        adult: false,
        gender: 2,
        id: 58528,
        known_for_department: 'Acting',
        name: 'James Urbaniak',
        original_name: 'James Urbaniak',
        popularity: 8.845,
        profile_path: '/7KUK2x6OI5XdPX5xrYAo9hxL49Z.jpg',
        cast_id: 371,
        character: 'Kurt Gödel',
        credit_id: '64bb362deb79c2013969df0f',
        order: 50,
      },
      {
        adult: false,
        gender: 2,
        id: 85151,
        known_for_department: 'Acting',
        name: 'Trond Fausa Aurvåg',
        original_name: 'Trond Fausa Aurvåg',
        popularity: 11.393,
        profile_path: '/rFWC22ZScaQwA85NBo7l1j9XQdo.jpg',
        cast_id: 141,
        character: 'George Kistiakowsky',
        credit_id: '6328afe8229ae200839ced9d',
        order: 51,
      },
      {
        adult: false,
        gender: 2,
        id: 90498,
        known_for_department: 'Acting',
        name: 'Devon Bostick',
        original_name: 'Devon Bostick',
        popularity: 23.6,
        profile_path: '/zAdSA85Plp7NzhQeM2w8heHWgEd.jpg',
        cast_id: 125,
        character: 'Seth Neddermeyer',
        credit_id: '6328af00aafebd007ba6fed5',
        order: 52,
      },
      {
        adult: false,
        gender: 2,
        id: 1448819,
        known_for_department: 'Acting',
        name: 'Danny Deferrari',
        original_name: 'Danny Deferrari',
        popularity: 6.178,
        profile_path: '/qdU56yVTNu0SsYqcngTEkIAyB3f.jpg',
        cast_id: 136,
        character: 'Enrico Fermi',
        credit_id: '6328af9b124c8d007d63c071',
        order: 53,
      },
      {
        adult: false,
        gender: 2,
        id: 61510,
        known_for_department: 'Acting',
        name: 'Christopher Denham',
        original_name: 'Christopher Denham',
        popularity: 9.534,
        profile_path: '/ffPY0KrV5KP9Nuv27m3JQU6j3Tq.jpg',
        cast_id: 132,
        character: 'Klaus Fuchs',
        credit_id: '6328af62aafebd007ba6feea',
        order: 54,
      },
      {
        adult: false,
        gender: 1,
        id: 2113468,
        known_for_department: 'Acting',
        name: 'Jessica Erin Martin',
        original_name: 'Jessica Erin Martin',
        popularity: 1.788,
        profile_path: '/2x5tuteEkVc7OMKReFYclB60U2A.jpg',
        cast_id: 357,
        character: 'Charlotte Serber',
        credit_id: '64bb24c8eb79c200c5d923f5',
        order: 55,
      },
      {
        adult: false,
        gender: 0,
        id: 2705767,
        known_for_department: 'Acting',
        name: 'Ronald Auguste',
        original_name: 'Ronald Auguste',
        popularity: 2.776,
        profile_path: '/nj5kTBzhi3wduSw4OT3uOzJGwM9.jpg',
        cast_id: 372,
        character: 'J. Ernest Wilkins',
        credit_id: '64bb36539d592c013ebd0c36',
        order: 56,
      },
      {
        adult: false,
        gender: 2,
        id: 25446,
        known_for_department: 'Acting',
        name: 'Máté Haumann',
        original_name: 'Máté Haumann',
        popularity: 2.744,
        profile_path: '/zRAKtRxg83R79LGUB6e6161QGJt.jpg',
        cast_id: 353,
        character: 'Leo Szilard',
        credit_id: '64b0833b20ecaf00c6f631ef',
        order: 57,
      },
      {
        adult: false,
        gender: 1,
        id: 52442,
        known_for_department: 'Acting',
        name: 'Olivia Thirlby',
        original_name: 'Olivia Thirlby',
        popularity: 10.699,
        profile_path: '/f6j1Y3C4Td3bmo8xQRGxC7zKgu0.jpg',
        cast_id: 143,
        character: 'Lilli Hornig',
        credit_id: '6328affd53866e007d80049b',
        order: 58,
      },
      {
        adult: false,
        gender: 2,
        id: 1499831,
        known_for_department: 'Acting',
        name: 'Jack Cutmore-Scott',
        original_name: 'Jack Cutmore-Scott',
        popularity: 8.991,
        profile_path: '/hqSKCld4ISWzgfAKfCt8xrGsWxb.jpg',
        cast_id: 373,
        character: 'Lyall Johnson',
        credit_id: '64bb36649d592c0124657858',
        order: 59,
      },
      {
        adult: false,
        gender: 2,
        id: 127281,
        known_for_department: 'Acting',
        name: 'Harrison Gilbertson',
        original_name: 'Harrison Gilbertson',
        popularity: 9.999,
        profile_path: '/f40KQcGF4LIXZunBVsqKg25VJmv.jpg',
        cast_id: 137,
        character: 'Philip Morrison',
        credit_id: '6328afab5cea18007d7efa85',
        order: 60,
      },
      {
        adult: false,
        gender: 2,
        id: 1736,
        known_for_department: 'Acting',
        name: 'James Remar',
        original_name: 'James Remar',
        popularity: 17.513,
        profile_path: '/ctMVpFDKKWCty60lLORf3IoJcv9.jpg',
        cast_id: 166,
        character: 'Henry Stimson',
        credit_id: '6387ba611b157d007a447369',
        order: 61,
      },
      {
        adult: false,
        gender: 2,
        id: 30791,
        known_for_department: 'Acting',
        name: 'Will Roberts',
        original_name: 'Will Roberts',
        popularity: 2.88,
        profile_path: '/4eiHqFEnZSJA8MZrKNEL1q1MSfx.jpg',
        cast_id: 374,
        character: 'George C. Marshall',
        credit_id: '64bb36899d592c00c7b0140e',
        order: 62,
      },
      {
        adult: false,
        gender: 2,
        id: 6326,
        known_for_department: 'Acting',
        name: 'Pat Skipper',
        original_name: 'Pat Skipper',
        popularity: 6.286,
        profile_path: '/83kKXFGLe1GDXc1lau63gD5W9uF.jpg',
        cast_id: 375,
        character: 'James Byrnes',
        credit_id: '64bb3698ac6c7900c7178c63',
        order: 63,
      },
      {
        adult: false,
        gender: 2,
        id: 80619,
        known_for_department: 'Acting',
        name: 'Steve Coulter',
        original_name: 'Steve Coulter',
        popularity: 6.853,
        profile_path: '/5bK6a5Cfy5DxVoNpzt4nbhUUW85.jpg',
        cast_id: 376,
        character: 'James Conant',
        credit_id: '64bb36a1af85de013a3e5224',
        order: 64,
      },
      {
        adult: false,
        gender: 0,
        id: 2075067,
        known_for_department: 'Acting',
        name: 'Jeremy John Wells',
        original_name: 'Jeremy John Wells',
        popularity: 2.176,
        profile_path: '/o47EmPu7GRL9jlhSOezgrrOmnxa.jpg',
        cast_id: 377,
        character: 'AAF Officer',
        credit_id: '64bb36a9fd4a960125491812',
        order: 65,
      },
      {
        adult: false,
        gender: 2,
        id: 543819,
        known_for_department: 'Acting',
        name: 'Sean Avery',
        original_name: 'Sean Avery',
        popularity: 0.817,
        profile_path: '/dgr9K0RvbjRdTNb6V2J25QJF68I.jpg',
        cast_id: 378,
        character: 'Weatherman',
        credit_id: '64bb36b2af85de011d7b4c39',
        order: 66,
      },
      {
        adult: false,
        gender: 2,
        id: 2614684,
        known_for_department: 'Acting',
        name: 'Adam Kroeger',
        original_name: 'Adam Kroeger',
        popularity: 4.294,
        profile_path: '/esKApCc6fcLekciUuZsrPDbuuwx.jpg',
        cast_id: 379,
        character: 'Army Captain',
        credit_id: '64bb36bdac6c7900e48d06dc',
        order: 67,
      },
      {
        adult: false,
        gender: 2,
        id: 1679557,
        known_for_department: 'Acting',
        name: 'Drew Kenney',
        original_name: 'Drew Kenney',
        popularity: 2.565,
        profile_path: '/w2t0hE68gKSfZ5tUlp9TFTKAf4V.jpg',
        cast_id: 380,
        character: 'Soldier',
        credit_id: '64bb36c5e9da6900cb7b398d',
        order: 68,
      },
      {
        adult: false,
        gender: 2,
        id: 65769,
        known_for_department: 'Acting',
        name: 'Bryce Johnson',
        original_name: 'Bryce Johnson',
        popularity: 7.417,
        profile_path: '/iyHjMvKijZZDVZkK681JAio4nAh.jpg',
        cast_id: 381,
        character: 'AAF Officer 2',
        credit_id: '64bb36ce58efd300ace11e56',
        order: 69,
      },
      {
        adult: false,
        gender: 1,
        id: 1505363,
        known_for_department: 'Acting',
        name: 'Flora Nolan',
        original_name: 'Flora Nolan',
        popularity: 5.397,
        profile_path: '/XYjrBJUmEFsb5IOTlnV2XeDpxz.jpg',
        cast_id: 354,
        character: 'Burn Victim',
        credit_id: '64b1b87578570e01008833ff',
        order: 70,
      },
      {
        adult: false,
        gender: 1,
        id: 2245154,
        known_for_department: 'Acting',
        name: 'Kerry Westcott',
        original_name: 'Kerry Westcott',
        popularity: 2.562,
        profile_path: '/a6LkiANuO65XXjAUVvHcxhN9Twz.jpg',
        cast_id: 382,
        character: 'Laughing Woman',
        credit_id: '64bb36d69d592c0102fea793',
        order: 71,
      },
      {
        adult: false,
        gender: 1,
        id: 1616338,
        known_for_department: 'Acting',
        name: 'Christina Hogue',
        original_name: 'Christina Hogue',
        popularity: 4.159,
        profile_path: '/8jpBmKvOcQ0FmxLR8xmOPMwGGl2.jpg',
        cast_id: 383,
        character: 'Kissing Woman',
        credit_id: '64bb36e0fd4a9600ae6480a2',
        order: 72,
      },
      {
        adult: false,
        gender: 2,
        id: 2767277,
        known_for_department: 'Acting',
        name: 'Clay Bunker',
        original_name: 'Clay Bunker',
        popularity: 1.62,
        profile_path: '/kZdi9GKA9IQ8rq7twPJaa21jytt.jpg',
        cast_id: 384,
        character: 'Kissing Man',
        credit_id: '64bb36e785c0a201060f4286',
        order: 73,
      },
      {
        adult: false,
        gender: 2,
        id: 3853422,
        known_for_department: 'Acting',
        name: 'Tyler Beardsley',
        original_name: 'Tyler Beardsley',
        popularity: 4.217,
        profile_path: '/msjVl2mx3f6ueO5jqQ2zTB2djP3.jpg',
        cast_id: 385,
        character: 'Weeping Man',
        credit_id: '64bb36ee85c0a200c8973ec3',
        order: 74,
      },
      {
        adult: false,
        gender: 1,
        id: 4174034,
        known_for_department: 'Acting',
        name: 'Maria Teresa Zuppetta',
        original_name: 'Maria Teresa Zuppetta',
        popularity: 2.278,
        profile_path: '/4g7MsOr4afJUUop7s9zKPQnpj7Y.jpg',
        cast_id: 386,
        character: 'Consoling Woman',
        credit_id: '64bb36f7ac6c79011e873b77',
        order: 75,
      },
      {
        adult: false,
        gender: 1,
        id: 1215055,
        known_for_department: 'Acting',
        name: 'Kate French',
        original_name: 'Kate French',
        popularity: 2.583,
        profile_path: '/t6yEREUpsFtX4W0pmP8EuOT8jGz.jpg',
        cast_id: 387,
        character: 'Presidential Aide',
        credit_id: '64bb36ffac6c7900afd4fb52',
        order: 76,
      },
      {
        adult: false,
        gender: 2,
        id: 64,
        known_for_department: 'Acting',
        name: 'Gary Oldman',
        original_name: 'Gary Oldman',
        popularity: 34.502,
        profile_path: '/2v9FVVBUrrkW2m3QOcYkuhq9A6o.jpg',
        cast_id: 128,
        character: 'Harry Truman',
        credit_id: '6328af2393bd69007f651850',
        order: 77,
      },
      {
        adult: false,
        gender: 2,
        id: 101661,
        known_for_department: 'Acting',
        name: 'Hap Lawrence',
        original_name: 'Hap Lawrence',
        popularity: 3.246,
        profile_path: '/2T6Qg4eF7yMWE50Snk6n5XvA8FK.jpg',
        cast_id: 388,
        character: 'Lyndon Johnson',
        credit_id: '64bb3707eb79c200e28ca1dc',
        order: 78,
      },
      {
        adult: false,
        gender: 1,
        id: 3603785,
        known_for_department: 'Acting',
        name: 'Meg Schimelpfenig',
        original_name: 'Meg Schimelpfenig',
        popularity: 1.96,
        profile_path: '/pCFoh39cpYHeD6fZtSehcKsde5.jpg',
        cast_id: 154,
        character: "Senator's Assistant (uncredited)",
        credit_id: '6328b19bb18f320083df88d4',
        order: 79,
      },
      {
        adult: false,
        gender: 2,
        id: 3936714,
        known_for_department: 'Acting',
        name: 'Matt Snead',
        original_name: 'Matt Snead',
        popularity: 1.388,
        profile_path: '/lqhW1t9v0gtTtKckljKjT1ee12a.jpg',
        cast_id: 398,
        character: 'Reporter (uncredited)',
        credit_id: '64d1549e549dda00e2de4e68',
        order: 80,
      },
      {
        adult: false,
        gender: 2,
        id: 3809152,
        known_for_department: 'Acting',
        name: 'Troy Bronson',
        original_name: 'Troy Bronson',
        popularity: 1.22,
        profile_path: '/g79Zkua1qgxZZg8voxPGqwMpEwa.jpg',
        cast_id: 400,
        character: 'Joseph W. Kennedy (uncredited)',
        credit_id: '6561896a3679a10978736c97',
        order: 81,
      },
      {
        adult: false,
        gender: 2,
        id: 3909469,
        known_for_department: 'Acting',
        name: 'Andrew Bursiaga',
        original_name: 'Andrew Bursiaga',
        popularity: 1.62,
        profile_path: '/q0LgQCTL9mQGN2nyKsj8DFfF4c2.jpg',
        cast_id: 403,
        character: 'Male Student (uncredited)',
        credit_id: '65824ee83a48c5218caf680b',
        order: 82,
      },
    ],
  },
};
