import type { Meta, StoryObj } from '@storybook/react';

import { RecommendationMedia } from '@lib/features/Movie/types';
import RecommendationsCarousel from './RecommendationsCarousel';

const meta: Meta<typeof RecommendationsCarousel> = {
  component: RecommendationsCarousel,
};

export default meta;

type Story = StoryObj<
  typeof RecommendationsCarousel<
    RecommendationMedia,
    keyof RecommendationMedia,
    keyof RecommendationMedia,
    keyof RecommendationMedia,
    keyof RecommendationMedia
  >
>;

export const Default: Story = {
  args: {
    recommendations: [
      {
        adult: false,
        backdrop_path: '/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg',
        id: 346698,
        title: 'Barbie',
        original_language: 'en',
        original_title: 'Barbie',
        overview:
          'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
        poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
        media_type: 'movie',
        genre_ids: [35, 12],
        popularity: 272.324,
        release_date: '2023-07-19',
        video: false,
        vote_average: 7.1,
        vote_count: 7927,
      },
      {
        adult: false,
        backdrop_path: '/kjQBrc00fB2RjHZB3PGR4w9ibpz.jpg',
        id: 670292,
        title: 'The Creator',
        original_language: 'en',
        original_title: 'The Creator',
        overview:
          'Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.',
        poster_path: '/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg',
        media_type: 'movie',
        genre_ids: [28, 12, 878],
        popularity: 130.069,
        release_date: '2023-09-27',
        video: false,
        vote_average: 7.093,
        vote_count: 2501,
      },
      {
        adult: false,
        backdrop_path: '/628Dep6AxEtDxjZoGP78TsOxYbK.jpg',
        id: 575264,
        title: 'Mission: Impossible - Dead Reckoning Part One',
        original_language: 'en',
        original_title: 'Mission: Impossible - Dead Reckoning Part One',
        overview:
          "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission—not even the lives of those he cares about most.",
        poster_path: '/NNxYkU70HPurnNCSiCjYAmacwm.jpg',
        media_type: 'movie',
        genre_ids: [28, 53],
        popularity: 156.24,
        release_date: '2023-07-08',
        video: false,
        vote_average: 7.6,
        vote_count: 3301,
      },
      {
        adult: false,
        backdrop_path: '/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg',
        id: 447365,
        title: 'Guardians of the Galaxy Vol. 3',
        original_language: 'en',
        original_title: 'Guardians of the Galaxy Vol. 3',
        overview:
          'Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.',
        poster_path: '/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
        media_type: 'movie',
        genre_ids: [878, 12, 28],
        popularity: 159.219,
        release_date: '2023-05-03',
        video: false,
        vote_average: 7.975,
        vote_count: 6134,
      },
      {
        adult: false,
        backdrop_path: '/7NRGAtu8E4343NSKwhkgmVRDINw.jpg',
        id: 507089,
        title: "Five Nights at Freddy's",
        original_language: 'en',
        original_title: "Five Nights at Freddy's",
        overview:
          "Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.",
        poster_path: '/A4j8S6moJS2zNtRR8oWF08gRnL5.jpg',
        media_type: 'movie',
        genre_ids: [27, 9648],
        popularity: 154.06,
        release_date: '2023-10-25',
        video: false,
        vote_average: 7.657,
        vote_count: 3514,
      },
      {
        adult: false,
        backdrop_path: '/1X7vow16X7CnCoexXh4H4F2yDJv.jpg',
        id: 466420,
        title: 'Killers of the Flower Moon',
        original_language: 'en',
        original_title: 'Killers of the Flower Moon',
        overview:
          'When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.',
        poster_path: '/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg',
        media_type: 'movie',
        genre_ids: [80, 36, 18],
        popularity: 139.987,
        release_date: '2023-10-18',
        video: false,
        vote_average: 7.498,
        vote_count: 2712,
      },
      {
        adult: false,
        backdrop_path: '/yF1eOkaYvwiORauRCPWznV9xVvi.jpg',
        id: 298618,
        title: 'The Flash',
        original_language: 'en',
        original_title: 'The Flash',
        overview:
          "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
        poster_path: '/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg',
        media_type: 'movie',
        genre_ids: [28, 12, 878],
        popularity: 217.728,
        release_date: '2023-06-13',
        video: false,
        vote_average: 6.756,
        vote_count: 3784,
      },
      {
        adult: false,
        backdrop_path: '/qB9wshRySHgN2MibLOlsW6YalqD.jpg',
        id: 945729,
        title: 'A Haunting in Venice',
        original_language: 'en',
        original_title: 'A Haunting in Venice',
        overview:
          'Celebrated sleuth Hercule Poirot, now retired and living in self-imposed exile in Venice, reluctantly attends a Halloween séance at a decaying, haunted palazzo. When one of the guests is murdered, the detective is thrust into a sinister world of shadows and secrets.',
        poster_path: '/l6iwxT0NbVw6QiF08YTIuTnXS82.jpg',
        media_type: 'movie',
        genre_ids: [9648, 53, 80],
        popularity: 56.673,
        release_date: '2023-09-13',
        video: false,
        vote_average: 6.703,
        vote_count: 1933,
      },
      {
        adult: false,
        backdrop_path: '/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
        id: 157336,
        title: 'Interstellar',
        original_language: 'en',
        original_title: 'Interstellar',
        overview:
          'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
        poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        media_type: 'movie',
        genre_ids: [12, 18, 878],
        popularity: 174.689,
        release_date: '2014-11-05',
        video: false,
        vote_average: 8.432,
        vote_count: 34012,
      },
      {
        adult: false,
        backdrop_path: '/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
        id: 569094,
        title: 'Spider-Man: Across the Spider-Verse',
        original_language: 'en',
        original_title: 'Spider-Man: Across the Spider-Verse',
        overview:
          'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.',
        poster_path: '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
        media_type: 'movie',
        genre_ids: [16, 28, 12, 878],
        popularity: 208.911,
        release_date: '2023-05-31',
        video: false,
        vote_average: 8.377,
        vote_count: 6090,
      },
      {
        adult: false,
        backdrop_path: '/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg',
        id: 502356,
        title: 'The Super Mario Bros. Movie',
        original_language: 'en',
        original_title: 'The Super Mario Bros. Movie',
        overview:
          'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
        poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
        media_type: 'movie',
        genre_ids: [16, 10751, 12, 14, 35],
        popularity: 241.033,
        release_date: '2023-04-05',
        video: false,
        vote_average: 7.683,
        vote_count: 8257,
      },
      {
        adult: false,
        backdrop_path: '/pA4sNvcohTNPx3AhEEeIu8gSt7h.jpg',
        id: 976573,
        title: 'Elemental',
        original_language: 'en',
        original_title: 'Elemental',
        overview:
          'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.',
        poster_path: '/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg',
        media_type: 'movie',
        genre_ids: [16, 35, 10751, 14, 10749, 12],
        popularity: 212.883,
        release_date: '2023-06-14',
        video: false,
        vote_average: 7.7,
        vote_count: 3903,
      },
      {
        adult: false,
        backdrop_path: '/gcbZ2ZdVzfBsGmfjTy8g7UaZS16.jpg',
        id: 747188,
        title: 'Asteroid City',
        original_language: 'en',
        original_title: 'Asteroid City',
        overview:
          'In an American desert town circa 1955, the itinerary of a Junior Stargazer/Space Cadet convention is spectacularly disrupted by world-changing events.',
        poster_path: '/qdq40gRS8xKnpFt5V75t6lUHgpx.jpg',
        media_type: 'movie',
        genre_ids: [35, 18],
        popularity: 40.351,
        release_date: '2023-06-08',
        video: false,
        vote_average: 6.494,
        vote_count: 1538,
      },
      {
        adult: false,
        backdrop_path: '/35z8hWuzfFUZQaYog8E9LsXW3iI.jpg',
        id: 335977,
        title: 'Indiana Jones and the Dial of Destiny',
        original_language: 'en',
        original_title: 'Indiana Jones and the Dial of Destiny',
        overview:
          "Finding himself in a new era, and approaching retirement, Indy wrestles with fitting into a world that seems to have outgrown him. But as the tentacles of an all-too-familiar evil return in the form of an old rival, Indy must don his hat and pick up his whip once more to make sure an ancient and powerful artifact doesn't fall into the wrong hands.",
        poster_path: '/Af4bXE63pVsb2FtbW8uYIyPBadD.jpg',
        media_type: 'movie',
        genre_ids: [12, 28],
        popularity: 114.153,
        release_date: '2023-06-28',
        video: false,
        vote_average: 6.598,
        vote_count: 2951,
      },
      {
        adult: false,
        backdrop_path: '/eHMh7kChaNeD4VTdMCXLJbRTzcI.jpg',
        id: 753342,
        title: 'Napoleon',
        original_language: 'en',
        original_title: 'Napoleon',
        overview:
          'An epic that details the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power through the prism of his addictive, volatile relationship with his wife, Josephine.',
        poster_path: '/vcZWJGvB5xydWuUO1vaTLI82tGi.jpg',
        media_type: 'movie',
        genre_ids: [18, 36, 10752],
        popularity: 193.344,
        release_date: '2023-11-22',
        video: false,
        vote_average: 6.485,
        vote_count: 1952,
      },
      {
        adult: false,
        backdrop_path: '/46Os8U0DEPmI0OnvKDxucl6SLVZ.jpg',
        id: 1008042,
        title: 'Talk to Me',
        original_language: 'en',
        original_title: 'Talk to Me',
        overview:
          'When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.',
        poster_path: '/kdPMUMJzyYAc4roD52qavX0nLIC.jpg',
        media_type: 'movie',
        genre_ids: [27, 53],
        popularity: 108.062,
        release_date: '2023-07-26',
        video: false,
        vote_average: 7.186,
        vote_count: 2469,
      },
      {
        adult: false,
        backdrop_path: '/xFYpUmB01nswPgbzi8EOCT1ZYFu.jpg',
        id: 980489,
        title: 'Gran Turismo',
        original_language: 'en',
        original_title: 'Gran Turismo',
        overview:
          'The ultimate wish-fulfillment tale of a teenage Gran Turismo player whose gaming skills won him a series of Nissan competitions to become an actual professional racecar driver.',
        poster_path: '/51tqzRtKMMZEYUpSYkrUE7v9ehm.jpg',
        media_type: 'movie',
        genre_ids: [12, 28, 18],
        popularity: 143.492,
        release_date: '2023-08-09',
        video: false,
        vote_average: 7.862,
        vote_count: 2247,
      },
      {
        adult: false,
        backdrop_path: '/xzdOIL7261CWehsHOk3lnP0xqam.jpg',
        id: 565770,
        title: 'Blue Beetle',
        original_language: 'en',
        original_title: 'Blue Beetle',
        overview:
          'Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab.',
        poster_path: '/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg',
        media_type: 'movie',
        genre_ids: [28, 878, 12],
        popularity: 114.951,
        release_date: '2023-08-16',
        video: false,
        vote_average: 6.8,
        vote_count: 2301,
      },
      {
        adult: false,
        backdrop_path: '/P3GAbRjzVo9RKU4WxzvtgwlITc.jpg',
        id: 678512,
        title: 'Sound of Freedom',
        original_language: 'en',
        original_title: 'Sound of Freedom',
        overview:
          'The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.',
        poster_path: '/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg',
        media_type: 'movie',
        genre_ids: [28, 18],
        popularity: 113.179,
        release_date: '2023-07-03',
        video: false,
        vote_average: 8.038,
        vote_count: 2083,
      },
      {
        adult: false,
        backdrop_path: '/5mzr6JZbrqnqD8rCEvPhuCE5Fw2.jpg',
        id: 615656,
        title: 'Meg 2: The Trench',
        original_language: 'en',
        original_title: 'Meg 2: The Trench',
        overview:
          'An exploratory dive into the deepest depths of the ocean of a daring research team spirals into chaos when a malevolent mining operation threatens their mission and forces them into a high-stakes battle for survival.',
        poster_path: '/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg',
        media_type: 'movie',
        genre_ids: [28, 878, 27],
        popularity: 165.127,
        release_date: '2023-08-02',
        video: false,
        vote_average: 6.589,
        vote_count: 3046,
      },
      {
        adult: false,
        backdrop_path: '/7I6VUdPj6tQECNHdviJkUHD2u89.jpg',
        id: 603692,
        title: 'John Wick: Chapter 4',
        original_language: 'en',
        original_title: 'John Wick: Chapter 4',
        overview:
          'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
        poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
        media_type: 'movie',
        genre_ids: [28, 53, 80],
        popularity: 202.044,
        release_date: '2023-03-22',
        video: false,
        vote_average: 7.743,
        vote_count: 5784,
      },
    ],
    poster_path: 'poster_path',
    release_date_path: 'release_date',
    id_path: 'id',
    name_path: 'title',
  },
};
